name: EtumAtrium
version: '${project.version}'
main: net.etum.etumatrium.Main
api-version: '1.20'
commands:
  atrium:
    permission: atrium.use
    aliases:
      - system
    description: command for manage server
  gamemode:
    permission: gamemode.use
    aliases:
      - gm
    description: command for change gamemode
