
# Settings for the plugin
MODULE:
  ConnectionManager:
    enable: true
    message:
      join: "&7[&a+&7] %player%"
      quit: "&7[&c-&7] %player%"
      welcome:
        - "Bienvenue "
        - "petit joueur"
  MOTD:
    enable: true
    message:
      - "MOTD LINE 1"
      - "MOTD LINE 2"


